[package]
name = "osm-graph"
version = "0.1.0"
edition = "2021"

[dependencies]
ordered-float = "4.2.2"
petgraph = "0.6.5"
plotters = "0.3.6"
reqwest = { version = "0.12.5", features = ["json", "blocking"] }
serde = { version = "1.0.204", features = ["derive"] }
serde_json = "1.0.121"
