[package]
name = "osm-graph"
version = "0.1.0"
edition = "2021"

[dev-dependencies]
plotters = "0.3.6"

[dependencies]
petgraph = "0.6.5"
reqwest = { version = "0.12.5", features = ["json", "blocking"] }
serde = { version = "1.0.204", features = ["derive"] }
serde_json = "1.0.121"
